version: '3'
services:
  vgs-django-sample:
    build: .
    ports:
      - 8000:8000
    environment:
      - CHECKER_HOST=https://api.checkr.com
      - CHECKER_API_KEY=some_api_key
  vgs-django-nginx:
    image: nginx
    volumes:
     - ./nginx/django_nginx.conf.template:/etc/nginx/conf.d/django_nginx.conf.template
    ports:
     - "8001:8001"
    environment:
     - DJANGO_APP_URL=http://vgs-django-sample:8000
     - VGS_INBOUND_URL=http://vgs-django-sample:8000
#     - VGS_INBOUND_URL=https://tntvsu7b08w.SANDBOX.verygoodproxy.com
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/django_nginx.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf &&nginx -g 'daemon off;'"
